### ISSUE TITLE
Android builds broken

### ISSUE THREAD

**Issue by Coolthulhu** [cataclysmbnteam/Cataclysm-BN#2243]
### Describe the bug

```
   /home/runner/work/Cataclysm-BN/Cataclysm-BN/android/app/jni/src/mutation_ui.cpp:245:35: error: use of undeclared identifier 'my_mutations'
          ctxt.register_manual_key( my_mutations[p].key, p.obj().name() );
                                    ^
  /home/runner/work/Cataclysm-BN/Cataclysm-BN/android/app/jni/src/mutation_ui.cpp:248:35: error: use of undeclared identifier 'my_mutations'
          ctxt.register_manual_key( my_mutations[a].key, a.obj().name() );
                                    ^
  2 errors generated.
```

Seems to have been caused in #2208 or so, since it's the PR that modified mutation UI code.
Probably a simple fix, like adding `who.` before the `my_mutations` bit.

### Steps To Reproduce

https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/3720157389/jobs/6309677665#step:18:1850

### Versions and configuration

Github actions

### Additional context

We might want to add android builds to the general PR test pipeline to catch those problems earlier.
