### ISSUE TITLE
Compilation fails with g++ on linux

### ISSUE THREAD

**Issue by gcaliber** [cataclysmbnteam/Cataclysm-BN#800]
Error when trying to compile on linux with g++ version 11.1.0. I was able to compile with clang successfully.

`$ make -j12 ASTYLE=0 LINTJSON=0 RELEASE=1 CCACHE=1 LUA=1 LTO=1 SOUND=0 LOCALIZE=0 RUNTESTS=0 BACKTRACE=0`

```
src/veh_interact.cpp: In lambda function:
src/veh_interact.cpp:707:46: error: loop variable ‘it’ of type ‘const std::pair<string_id<Skill>, int>&’ binds to a temporary constructed from type ‘const std::pair<const string_id<Skill>, int>’ [-Werror=range-loop-construct]
  707 |         for( const std::pair<skill_id, int> &it : vpi.install_skills ) {
      |                                              ^~
src/veh_interact.cpp:707:46: note: use non-reference type ‘const std::pair<string_id<Skill>, int>’ to make the copy explicit or ‘const std::pair<const string_id<Skill>, int>&’ to prevent copying
src/veh_interact.cpp: At top level:
cc1plus: note: unrecognized command-line option ‘-Wno-range-loop-analysis’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
cc1plus: all warnings being treated as errors
make: *** [Makefile:871: obj/veh_interact.o] Error 1
make: *** Waiting for unfinished jobs....
```
